# permissions for end users to edit azuefilecsiconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azuefilecsiconfig-editor-role
rules:
- apiGroups:
  - csi.tanzu.vmware.com
  resources:
  - azurefilecsiconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.tanzu.vmware.com
  resources:
  - azurefilecsiconfigs/status
  verbs:
  - get